image: docker:latest

stages:
  - build
  - push
  - deploy

build:
  stage: build
  script:
    - docker pull homeassistant/home-assistant:latest
    - docker build -t quay.io/vitaly/hass .

push:
  stage: push
  script:
    - docker push quay.io/vitaly/hass

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --stack Automation --service Home-assistant --environment Home --no-start-before-stopping
